language: go
go:
- tip
sudo: false
install:
- go generate
- go get -u -v $(go list -f '{{join .Imports "\n"}}' ./... | sort | uniq | grep -v caddy-filemanager)
- go get -u github.com/caddyserver/caddydev
- go install github.com/caddyserver/caddydev
script:
- caddydev --output="caddy" --source="." filemanager
